### ISSUE TITLE
Node 22 error on build

### ISSUE THREAD

**Issue by luca-peruzzo** [keycloakify/keycloakify-angular#24]
```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'PATH/node_modules/@keycloakify/angular/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at eval (eval at 653 (file://PATH/node_modules/@keycloakify/angular/bin/main.js:7:18), <anonymous>:1:1)
    at 653 (file://PATH/node_modules/@keycloakify/angular/bin/main.js:7:18)
    at __nccwpck_require__ (file://PATH/node_modules/@keycloakify/angular/bin/main.js:34:41)
    at file://PATH/node_modules/@keycloakify/angular/bin/main.js:197:63
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.11.0
```

**Comment by garronej** [comment]
Hello @luca-peruzzo,  

This is something that I should fix indeed.  
I know exactly what the problem is, I was just too lazy to fix it 😂
